sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=default-debian-8
  - INSTANCE=default-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=native-centos-7
  - INSTANCE=native-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=scl-centos-7
  - INSTANCE=scl-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=replication-centos-7
  - INSTANCE=replication-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=replication-debian-8
  - INSTANCE=replication-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=replication-ubuntu-1604
  - INSTANCE=replication-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=galera-centos-7
  - INSTANCE=galera-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=galera-debian-8
  - INSTANCE=galera-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=galera-ubuntu-1604
  - INSTANCE=galera-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=datadir-changed-centos-7
  - INSTANCE=datadir-changed-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=datadir-changed-debian-8
  - INSTANCE=datadir-changed-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=datadir-changed-ubuntu-1604
  - INSTANCE=datadir-changed-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=port-changed-centos-7
  - INSTANCE=port-changed-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=port-changed-debian-8
  - INSTANCE=port-changed-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=port-changed-ubuntu-1604
  - INSTANCE=port-changed-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=plugins-centos-7
  - INSTANCE=plugins-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=plugins-debian-8
  - INSTANCE=plugins-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=plugins-ubuntu-1604
  - INSTANCE=plugins-ubuntu-1604 CHEF_VERSION=12.19.36
  - INSTANCE=no-binlog-centos-7
  - INSTANCE=no-binlog-centos-7 CHEF_VERSION=12.19.36
  - INSTANCE=no-binlog-debian-8
  - INSTANCE=no-binlog-debian-8 CHEF_VERSION=12.19.36
  - INSTANCE=no-binlog-ubuntu-1604
  - INSTANCE=no-binlog-ubuntu-1604 CHEF_VERSION=12.19.36

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)" && chef gem install berkshelf
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  allow_failures:
    - env: INSTANCE=default-centos-7
    - env: INSTANCE=default-debian-8
    - env: INSTANCE=default-ubuntu-1604
    - env: INSTANCE=native-centos-7
    - env: INSTANCE=scl-centos-7
    - env: INSTANCE=replication-centos-7
    - env: INSTANCE=replication-debian-8
    - env: INSTANCE=replication-ubuntu-1604
    - env: INSTANCE=galera-centos-7
    - env: INSTANCE=galera-debian-8
    - env: INSTANCE=galera-ubuntu-1604
    - env: INSTANCE=datadir-changed-centos-7
    - env: INSTANCE=datadir-changed-debian-8
    - env: INSTANCE=datadir-changed-ubuntu-1604
    - env: INSTANCE=port-changed-centos-7
    - env: INSTANCE=port-changed-debian-8
    - env: INSTANCE=port-changed-ubuntu-1604
    - env: INSTANCE=plugins-centos-7
    - env: INSTANCE=plugins-debian-8
    - env: INSTANCE=plugins-ubuntu-1604
    - env: INSTANCE=no-binlog-centos-7
    - env: INSTANCE=no-binlog-debian-8
    - env: INSTANCE=no-binlog-ubuntu-1604
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
