sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=repository-centos-6
  - INSTANCE=repository-centos-6 CHEF_VERSION=14.2.0
  - INSTANCE=repository-centos-7
  - INSTANCE=repository-centos-7 CHEF_VERSION=14.2.0
  - INSTANCE=repository-debian-8
  - INSTANCE=repository-debian-8 CHEF_VERSION=14.2.0
  - INSTANCE=repository-debian-9
  - INSTANCE=repository-debian-9 CHEF_VERSION=14.2.0
  - INSTANCE=repository-ubuntu-1604
  - INSTANCE=repository-ubuntu-1604 CHEF_VERSION=14.2.0
  - INSTANCE=repository-ubuntu-1804
  - INSTANCE=repository-ubuntu-1804 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-centos-6
  - INSTANCE=client-install-centos-6 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-centos-7
  - INSTANCE=client-install-centos-7 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-debian-8
  - INSTANCE=client-install-debian-8 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-debian-9
  - INSTANCE=client-install-debian-9 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-ubuntu-1604
  - INSTANCE=client-install-ubuntu-1604 CHEF_VERSION=14.2.0
  - INSTANCE=client-install-ubuntu-1804
  - INSTANCE=client-install-ubuntu-1804 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-centos-6
  - INSTANCE=server-install-centos-6 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-centos-7
  - INSTANCE=server-install-centos-7 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-debian-8
  - INSTANCE=server-install-debian-8 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-debian-9
  - INSTANCE=server-install-debian-9 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-ubuntu-1604
  - INSTANCE=server-install-ubuntu-1604 CHEF_VERSION=14.2.0
  - INSTANCE=server-install-ubuntu-1804
  - INSTANCE=server-install-ubuntu-1804 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-centos-6
  - INSTANCE=server-configuration-centos-6 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-centos-7
  - INSTANCE=server-configuration-centos-7 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-debian-8
  - INSTANCE=server-configuration-debian-8 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-debian-9
  - INSTANCE=server-configuration-debian-9 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-ubuntu-1604
  - INSTANCE=server-configuration-ubuntu-1604 CHEF_VERSION=14.2.0
  - INSTANCE=server-configuration-ubuntu-1804
  - INSTANCE=server-configuration-ubuntu-1804 CHEF_VERSION=14.2.0
  - INSTANCE=resources-centos-6
  - INSTANCE=resources-centos-6 CHEF_VERSION=14.2.0
  - INSTANCE=resources-centos-7
  - INSTANCE=resources-centos-7 CHEF_VERSION=14.2.0
  - INSTANCE=resources-debian-8
  - INSTANCE=resources-debian-8 CHEF_VERSION=14.2.0
  - INSTANCE=resources-debian-9
  - INSTANCE=resources-debian-9 CHEF_VERSION=14.2.0
  - INSTANCE=resources-ubuntu-1604
  - INSTANCE=resources-ubuntu-1604 CHEF_VERSION=14.2.0
  - INSTANCE=resources-ubuntu-1804
  - INSTANCE=resources-ubuntu-1804 CHEF_VERSION=14.2.0

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)" && chef gem install chef-dk
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  allow_failures:
  - env: INSTANCE=server-install-ubuntu-1804
  - env: INSTANCE=server-install-ubuntu-1804 CHEF_VERSION=14.2.0
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
